name: Node_Project_1
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: install_node_js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            - name: install_deps
              run: npm ci
            - name: run_test
              run: npm run